// Shared default configurations that can be used by both frontend and backend

export const DEFAULT_CONFIGS = {
  sampletypes: [
    { label: "Animal", value: "animal", description: "Animal individual", shortened: "an" },
    { label: "Blood", value: "blood", description: "Blood sample", shortened: "bl" },
    { label: "DNA extract", value: "dna_extract", description: "DNA extract", shortened: "dna" },
    { label: "Tissue", value: "tissue", description: "Tissue sample", shortened: "ti" },
    { label: "Secretion", value: "secretion", description: "Secretion sample", shortened: "se" }
  ],
  traittypes: [
    { value: "mass", label: "Mass", unit: "g", description: "Mass of the sample measured using a microbalance" },
    { value: "length", label: "Length", unit: "mm", description: "Length of the sample measured from maximum to minimum point along the longest symmetry axis" },
    { value: "width", label: "Width", unit: "mm", description: "Width of the sample measured from maximum to minimum point along the perpendicular to the longest symmetry axis" },
    { value: "dna_concentration", label: "DNA concentration", unit: "ng/µl", description: "DNA concentration of the sample" },
    { value: "resting_metabolic_rate", label: "Resting metabolic rate", unit: "W", description: "Metabolic rate measured by respirometry at rest" },
    { value: "fiber_diameter", label: "Fibre diameter", unit: "μm", description: "Diameter of individual fibres" },
    { value: "tensile_strength", label: "Tensile strength", unit: "MPa", description: "Maximum stress material can withstand while being stretched" },
    { value: "bone_density", label: "Bone density", unit: "g/cm³", description: "Density of bone tissue" },
    { value: "cortical_thickness", label: "Cortical thickness", unit: "mm", description: "Thickness of cortical bone layer" }
  ],
  equipmenttypes: [
    { label: "Haematology analyser", value: "hematology_analyzer", description: "Haematology analyser" },
    { label: "Flow cytometer", value: "flow_cytometer", description: "Flow cytometer" },
    { label: "Optical microscope", value: "optical_microscope", description: "Optical microscope" },
    { label: "SEM", value: "SEM", description: "Scanning electron microscope" },
    { label: "TEM", value: "TEM", description: "Transmission electron microscope" },
    { label: "AFM", value: "AFM", description: "Atomic force microscope" },
    { label: "PCR machine", value: "PCR_machine", description: "Polymerase chain reaction machine" },
    { label: "Gel electrophoresis", value: "gel_electrophoresis", description: "Gel electrophoresis" },
    { label: "Raman", value: "Raman", description: "Raman spectroscopy" },
    { label: "FTIR", value: "FTIR", description: "Fourier transform infrared spectroscopy" },
    { label: "UV-Vis", value: "UV-Vis", description: "UV-Vis spectroscopy" },
    { label: "Fluorescence", value: "Fluorescence", description: "Fluorescence spectroscopy" }
  ],
  samplesubtypes: [
    { value: "whole_blood", label: "Whole blood", shortened: "wb", description: "Whole blood sample" },
    { value: "serum", label: "Serum", shortened: "se", description: "Serum sample" },
    { value: "plasma", label: "Plasma", shortened: "pl", description: "Plasma sample" },
    { value: "buffy_coat", label: "Buffy coat", shortened: "bc", description: "Buffy coat sample" },
    { value: "genomic_dna", label: "Genomic DNA", shortened: "gd", description: "Genomic DNA" },
    { value: "cdna", label: "cDNA", shortened: "cd", description: "Complementary DNA" },
    { value: "rna", label: "RNA", shortened: "rn", description: "Ribonucleic acid" },
    { value: "muscle", label: "Muscle", shortened: "mu", description: "Muscle tissue" },
    { value: "fat", label: "Fat", shortened: "fa", description: "Fat tissue" },
    { value: "skin", label: "Skin", shortened: "sk", description: "Skin tissue" },
    { value: "bone", label: "Bone", shortened: "bo", description: "Bone tissue" },
    { value: "organ", label: "Organ", shortened: "or", description: "Organ tissue" },
    { value: "gland", label: "Gland", shortened: "gl", description: "Gland tissue" },
    { value: "nerve", label: "Nerve", shortened: "ne", description: "Nerve tissue" },
    { value: "eye", label: "Eye", shortened: "ey", description: "Eye tissue" },
    { value: "gut", label: "Gut", shortened: "gu", description: "Gut tissue" },
    { value: "reproductive", label: "Reproductive", shortened: "re", description: "Reproductive tissue" },
    { value: "generic_speciment_subsample", label: "Generic specimen subsample", shortened: "gs", description: "Generic specimen subsample, e.g. a leg" },
    { value: "saliva", label: "Saliva", shortened: "sa", description: "Saliva sample" },
    { value: "venom", label: "Venom", shortened: "ve", description: "Venom sample" },
    { value: "mucus", label: "Mucus", shortened: "mu", description: "Mucus sample" },
    { value: "silk", label: "Silk", shortened: "si", description: "Silk sample" },
    { value: "sperm", label: "Sperm", shortened: "sp", description: "Sperm sample" },
    { value: "faeces", label: "Faeces", shortened: "fa", description: "Faeces sample" },
    { value: "urine", label: "Urine", shortened: "ur", description: "Urine sample" }
  ],
  silkcategories: [
    { value: "dragline", label: "Dragline", shortened: "dl" },
    { value: "attachment", label: "Attachment", shortened: "at" },
    { value: "cribellar net", label: "Cribellar net", shortened: "crn" },
    { value: "cribellar line", label: "Cribellar line", shortened: "crl" },
    { value: "cribellar web", label: "Cribellar web", shortened: "crw" },
    { value: "cocoon", label: "Cocoon", shortened: "cc" },
    { value: "eggsac", label: "Egg sac", shortened: "es" },
    { value: "flagelliform", label: "Flagelliform", shortened: "fl" },
    { value: "minor ampullate", label: "Minor", shortened: "mi" },
    { value: "major ampullate", label: "Major", shortened: "ma" },
    { value: "tubuliform", label: "Tubuliform", shortened: "tu" },
    { value: "aciniform", label: "Aciniform", shortened: "ac" },
    { value: "all fibres", label: "Fibres from all spinnerets", shortened: "al" },
    { value: "viscid", label: "Viscid", shortened: "vi" },
    { value: "unknown", label: "Unknown", shortened: "un" },
    { value: "prey wrap", label: "Prey wrap", shortened: "pw" },
    { value: "intercepted prey wrap", label: "Intercepted prey wrap", shortened: "ipw" },
    { value: "gumfoot", label: "Gumfoot", shortened: "gf" },
    { value: "sheet web", label: "Sheet web", shortened: "sw" },
    { value: "tangle web", label: "Tangle web", shortened: "tw" },
    { value: "capture thread", label: "Capture thread", shortened: "ct" },
    { value: "bridging line", label: "Bridging line", shortened: "bl" },
    { value: "retreat", label: "Retreat", shortened: "rt" },
    { value: "nest", label: "Nest", shortened: "ne" },
    { value: "scaffold", label: "Scaffold", shortened: "sc" },
    { value: "escape jump", label: "Escape jump", shortened: "ej" },
    { value: "manual collection", label: "Manual collection", shortened: "mc" },
    { value: "walking", label: "Fibres from walking", shortened: "wlk" },
    { value: "other", label: "Other", shortened: "ot" }
  ],
  siprefixes: [
    { label: "Yotta", value: "Y", power: 24 },
    { label: "Zetta", value: "Z", power: 21 },
    { label: "Exa", value: "E", power: 18 },
    { label: "Peta", value: "P", power: 15 },
    { label: "Tera", value: "T", power: 12 },
    { label: "Giga", value: "G", power: 9 },
    { label: "Mega", value: "M", power: 6 },
    { label: "Kilo", value: "k", power: 3 },
    { label: "Hecto", value: "h", power: 2 },
    { label: "Deka", value: "da", power: 1 },
    { label: "Deci", value: "d", power: -1 },
    { label: "Centi", value: "c", power: -2 },
    { label: "Milli", value: "m", power: -3 },
    { label: "Micro", value: "µ", power: -6 },
    { label: "Nano", value: "n", power: -9 },
    { label: "Pico", value: "p", power: -12 },
    { label: "Femto", value: "f", power: -15 },
    { label: "Atto", value: "a", power: -18 },
    { label: "Zepto", value: "z", power: -21 },
    { label: "Yocto", value: "y", power: -24 }
  ],
  baseunits: [
    { value: "m", label: "Meter", description: "SI unit of length", category: "length" },
    { value: "g", label: "Gram", description: "SI unit of mass", category: "mass" },
    { value: "s", label: "Second", description: "SI unit of time", category: "time" },
    { value: "A", label: "Ampere", description: "SI unit of electric current", category: "electric current" },
    { value: "K", label: "Kelvin", description: "SI unit of temperature", category: "temperature" },
    { value: "mol", label: "Mole", description: "SI unit of amount of substance", category: "amount" },
    { value: "cd", label: "Candela", description: "SI unit of luminous intensity", category: "luminous intensity" },
    { value: "Hz", label: "Hertz", description: "Unit of frequency", category: "frequency" },
    { value: "N", label: "Newton", description: "Unit of force", category: "force" },
    { value: "Pa", label: "Pascal", description: "Unit of pressure", category: "pressure" },
    { value: "J", label: "Joule", description: "Unit of energy", category: "energy" },
    { value: "W", label: "Watt", description: "Unit of power", category: "power" },
    { value: "C", label: "Coulomb", description: "Unit of electric charge", category: "electric charge" },
    { value: "V", label: "Volt", description: "Unit of voltage", category: "voltage" },
    { value: "F", label: "Farad", description: "Unit of capacitance", category: "capacitance" },
    { value: "Ω", label: "Ohm", description: "Unit of resistance", category: "resistance" },
    { value: "S", label: "Siemens", description: "Unit of conductance", category: "conductance" },
    { value: "Wb", label: "Weber", description: "Unit of magnetic flux", category: "magnetic flux" },
    { value: "T", label: "Tesla", description: "Unit of magnetic field", category: "magnetic field" },
    { value: "H", label: "Henry", description: "Unit of inductance", category: "inductance" },
    { value: "L", label: "Liter", description: "Unit of volume", category: "volume" },
    { value: "l", label: "Liter (lowercase)", description: "Unit of volume", category: "volume" }
  ]
};

// Individual exports for backward compatibility
export const sampletypes = DEFAULT_CONFIGS.sampletypes;
export const traittypes = DEFAULT_CONFIGS.traittypes;
export const equipmenttypes = DEFAULT_CONFIGS.equipmenttypes;
export const samplesubtypes = DEFAULT_CONFIGS.samplesubtypes;
export const silkcategories = DEFAULT_CONFIGS.silkcategories;
export const siprefixes = DEFAULT_CONFIGS.siprefixes;
export const baseunits = DEFAULT_CONFIGS.baseunits;
