services:
  docs:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run docs:dev -- --host 0.0.0.0

  docs-build:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run docs:build
    profiles:
      - build
