name: Deploy Documentation

on:
  push:
    branches: [ main, test-docs-workflow ]  # Add your test branch here
    paths: [ 'docs/**', 'src/app/api/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'src/app/api/**' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'daniele-liprandi'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Pages
        uses: actions/configure-pages@v4      
      
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --force
        working-directory: docs

      - name: Install main project dependencies for API spec generation
        run: |
          npm install swagger-jsdoc redoc-cli glob --save-dev
        working-directory: .

      - name: Generate OpenAPI spec
        run: |
          node scripts/generate-openapi-spec.js
        working-directory: .

      - name: Generate static API docs with Redoc
        run: |
          npx redoc-cli build openapi-spec.json --output docs/public/api-docs.html --title "EvoNEST API Documentation"
        working-directory: .

      - name: Build documentation
        run: npm run docs:build
        working-directory: docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
